ignore: [ '**/lib/generated/', 'lib/generated/', '**/*.g.dart', '**/*.gen.dart', '**/lib/di/', '**/lib/constants/', 'lib/constants/*.dart', 'lib/routers/router.dart' ]
coverage:
  status:
    project:
      default:
        target: 35%
        threshold: 1%
